// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEJmG09bd2qCCH1DbleZO-RPS64_oTw3Y',
    appId: '1:352305188284:web:f5b73a95e720c7b459efb9',
    messagingSenderId: '352305188284',
    projectId: 'insight-flow-9d43c',
    authDomain: 'insight-flow-9d43c.firebaseapp.com',
    storageBucket: 'insight-flow-9d43c.firebasestorage.app',
    measurementId: 'G-GJFJ0980JC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADUdpo8q-jtGVj-HRC34C25sIhOiOeIto',
    appId: '1:352305188284:android:6fa2e96beaf81e0e59efb9',
    messagingSenderId: '352305188284',
    projectId: 'insight-flow-9d43c',
    storageBucket: 'insight-flow-9d43c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0fqZ5X9fN82w6fRLEEHQH19W-DIRGT1k',
    appId: '1:352305188284:ios:ffb9d0a07cf2892959efb9',
    messagingSenderId: '352305188284',
    projectId: 'insight-flow-9d43c',
    storageBucket: 'insight-flow-9d43c.firebasestorage.app',
    iosBundleId: 'com.manuraj.insightFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0fqZ5X9fN82w6fRLEEHQH19W-DIRGT1k',
    appId: '1:352305188284:ios:ffb9d0a07cf2892959efb9',
    messagingSenderId: '352305188284',
    projectId: 'insight-flow-9d43c',
    storageBucket: 'insight-flow-9d43c.firebasestorage.app',
    iosBundleId: 'com.manuraj.insightFlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEJmG09bd2qCCH1DbleZO-RPS64_oTw3Y',
    appId: '1:352305188284:web:23a0a735affa8dda59efb9',
    messagingSenderId: '352305188284',
    projectId: 'insight-flow-9d43c',
    authDomain: 'insight-flow-9d43c.firebaseapp.com',
    storageBucket: 'insight-flow-9d43c.firebasestorage.app',
    measurementId: 'G-FPML7E0HRF',
  );
}
